// Pre-cleanup snapshot of the built-in template registries, captured
// VERBATIM from `git show HEAD:src/config.template.ts` (HEAD =
// `0aa054e`, the PRE-cleanup state — before the redundant `s_space`
// tokens were dropped). The s_space cleanup (vX.X.X+) removes the
// `s_space` tokens that the auto-space feature (prefixSpace, default
// true) now reproduces; these PRE_CLEANUP_* values retain the original
// tokens so the byte-identity guard in src/render-affix.test.ts can
// render each built-in BOTH ways under prefixSpace=true and assert the
// outputs are identical.
//
// DEFAULT_LINE_TEMPLATES.quota / .balance reference the shared
// DEFAULT_LINE_TEMPLATE arrays; the quota / balance bodies are inlined
// here (not referenced) so the snapshot is self-contained and survives
// edits to config.template.ts.

import type { LineTemplates, StatuslineTemplate } from "../config.template.ts";

export const PRE_CLEANUP_LINE_TEMPLATES: LineTemplates = {
  quota: [
    "m_modeLabel|color:yellow", "s_space",
    "m_windowQuota|term:short", "s_space", "m_countdown|term:short",
    "s_space", "s_dot", "s_space",
    "m_windowQuota|term:mid", "s_space", "m_countdown|term:mid",
    "s_space", "m_age"
  ],
  balance: ["m_modeLabel|color:yellow", "s_space", "m_balance", "s_space", "m_age"],

  quota_all: [
    "m_modeLabel|color:yellow", "s_space",
    "m_windowQuota|term:short", "s_space", "m_countdown|term:short",
    "~",
    "m_sumEstQuota|term:short|valueOnly:true",
    "s_dot|wrap:true",
    "m_windowQuota|term:mid", "s_space", "m_countdown|term:mid",
    "~",
    "m_sumEstQuota|term:mid|valueOnly:true",
    // "s_dot|wrap:true",
    // "m_windowQuota|term:long", "s_space", "m_countdown|term:long",
    // "~",
    // "m_sumEstQuota|term:long|valueOnly:true",
    "s_space", "m_age"
  ],

  quota_all_compact: [
    "m_modeLabel|color:yellow",
    "s_space",
    "m_windowQuota|term:short",
    "s_space",
    "m_countdown|term:short|valueOnly:true",
    "s_dot|wrap:true",
    "m_windowQuota|term:mid",
    "s_space",
    "m_countdown|term:mid|valueOnly:true",
    "s_dot|wrap:true",
    "m_windowQuota|term:long",
    "s_space",
    "m_countdown|term:long|valueOnly:true"
  ],

  plugin_info: [
    "m_label|CreditGauge |color:yellow",
    "m_version|color:yellow",
  ],

  tokens_tick: [
    "m_tokenInSpeed",
    "s_space",
    "m_tokenOutSpeed",
    "s_space",
    "m_tokenHitRate",
    "s_space",
    "m_apiMs",
    "s_space",
    "m_tokenIn",
    "s_space",
    "m_tokenOut",
    "s_space",
    "m_tokenCachedIn",
    "s_space",
    "m_tokenTotalIn",
    "s_space",
    "m_tokenCost"
  ],
  tokens_acc: [
    "m_accTokenInSpeed",
    "s_space",
    "m_accTokenOutSpeed",
    "s_space",
    "m_accTokenHitRate",
    "s_space",
    "m_accApiMs",
    "s_space",
    "m_accTokenIn",
    "s_space",
    "m_accTokenOut",
    "s_space",
    "m_accTokenCachedIn",
    "s_space",
    "m_accTokenTotalIn",
    "s_space",
    "m_accApiCalls",
    "s_space",
    "m_accTokenCost",
    "s_space",
    "m_accStartTime|abs:true",
  ],
  tokens_stat: [
    "m_sumTokenInSpeed",
    "s_space",
    "m_sumTokenOutSpeed",
    "s_space",
    "m_sumTokenHitRate",
    "s_space",
    "m_sumApiMs",
    "s_space",
    "m_sumTokenIn",
    "s_space",
    "m_sumTokenOut",
    "s_space",
    "m_sumTokenCachedIn",
    "s_space",
    "m_sumTokenTotalIn",
    "s_space",
    "m_sumApiCalls",
    "s_space",
    "m_sumTokenCost",
    "s_space",
    "m_sumStartTime|abs:true",
  ],
  information: [
    "[",
    "m_provider",
    "/",
    "m_model",
    "] ",
    "m_label|Context: |color:yellow",
    "m_windowContext|display:used",
    "s_space",
    "m_contextSize|valueOnly:true",
    "/",
    "m_contextWindowSize|valueOnly:true",
  ],
  mem_info: [
    "m_label|▦ Memory: |color:yellow",
    "m_windowMemUsage|display:used",
    "s_space",
    "m_memUsage|valueOnly:true",
  ],
  git_info: [
    "m_label|⎇ Git: |color:yellow",
    "m_branch|withStatus:true",
    "s_space",
    "m_linesAdded",
    "s_space",
    "m_linesRemoved",
  ],
  tick_eval: [
    "m_label|⚡Tick-tock: |color:cyan",
    "m_tokenInSpeed",
    "s_space",
    "m_tokenOutSpeed",
    "s_space",
    "m_tokenIn",
    "s_space",
    "m_tokenOut",
    "s_space",
    "m_apiMs",
    "s_space",
    "m_tokenCachedIn",
    "s_space",
    "m_tokenTotalIn",
    "s_space",
    "m_template|quote",
  ],
  combline1: [
    "m_label|🟢Session:   |color:orange",
    "m_accTokenInSpeed|scope:session",
    "s_space",
    "m_accTokenOutSpeed|scope:session",
    "s_space",
    "m_accTokenIn|scope:session",
    "s_space",
    "m_accTokenOut|scope:session",
    "s_space",
    "m_accTokenCachedIn|scope:session",
    "s_space",
    "m_accTokenHitRate|scope:session",
    "s_space",
    "m_accApiCalls|scope:session",
    "s_move|pos:73",
    "s_pipe|wrap:true",
    "m_label|⌛5h-align: |color:yellow",
    "m_sumTokenInSpeed|window:5h|align:true",
    "s_space",
    "m_sumTokenOutSpeed|window:5h|align:true",
    "s_space",
    "m_sumTokenIn|window:5h|align:true",
    "s_space",
    "m_sumTokenOut|window:5h|align:true",
    "s_space",
    "m_sumTokenCachedIn|window:5h|align:true",
    "s_space",
    "m_sumTokenHitRate|window:5h|align:true",
    "s_space",
    "m_sumApiCalls|window:5h|align:true",
  ],
  combline2: [
    "m_label|🟢Project:   |color:orange",
    "m_accTokenInSpeed|scope:project",
    "s_space",
    "m_accTokenOutSpeed|scope:project",
    "s_space",
    "m_accTokenIn|scope:project",
    "s_space",
    "m_accTokenOut|scope:project",
    "s_space",
    "m_accTokenCachedIn|scope:project",
    "s_space",
    "m_accTokenHitRate|scope:project",
    "s_space",
    "m_accApiCalls|scope:project",
    "s_move|pos:73",
    "s_pipe|wrap:true",
    "m_label|⌛7d-align: |color:yellow",
    "m_sumTokenInSpeed|window:7d|align:true",
    "s_space",
    "m_sumTokenOutSpeed|window:7d|align:true",
    "s_space",
    "m_sumTokenIn|window:7d|align:true",
    "s_space",
    "m_sumTokenOut|window:7d|align:true",
    "s_space",
    "m_sumTokenCachedIn|window:7d|align:true",
    "s_space",
    "m_sumTokenHitRate|window:7d|align:true",
    "s_space",
    "m_sumApiCalls|window:7d|align:true",
    "s_space",
    "m_statTtlStatus",
  ],
  "tickline-slim": [
    "m_label|⚡: |color:orange",
    "m_tokenOutSpeed",
    "s_space",
    "m_tokenIn",
    "s_space",
    "m_tokenOut",
    "s_space",
    "m_tokenCachedIn",
    "s_space",
    "m_tokenTotalIn",
    "s_space",
    "m_apiMs",
    "s_pipe|wrap:true",
    "m_session"
  ],
  "combline1-slim": [
    "m_label|🗪 : |color:orange",
    "m_accTokenOutSpeed|scope:session",
    "s_space",
    "m_accTokenOut|scope:session",
    "s_space",
    "m_accTokenTotalIn|scope:session",
    "s_space",
    "m_accTokenHitRate|scope:session",
    "s_space",
    "m_accApiCalls|scope:session",
    "s_move|pos:47",
    "s_pipe",
    "m_label|⌛5h: |color:yellow",
    "m_sumTokenOutSpeed|window:5h|align:true",
    "s_space",
    "m_sumTokenOut|window:5h|align:true",
    "s_space",
    "m_sumTokenTotalIn|window:5h|align:true",
    "s_space",
    "m_sumTokenHitRate|window:5h|align:true",
    "s_space",
    "m_sumApiCalls|window:5h|align:true",
    "s_space",
    "m_sumTokenCost|window:5h|align:true|valueOnly:true",
    "s_space",
    "m_statTtlStatus"
  ],
  "combline2-slim": [
    "m_label|📦: |color:orange",
    "m_accTokenOutSpeed|scope:project",
    "s_space",
    "m_accTokenOut|scope:project",
    "s_space",
    "m_accTokenTotalIn|scope:project",
    "s_space",
    "m_accTokenHitRate|scope:project",
    "s_space",
    "m_accApiCalls|scope:project",
    "s_move|pos:46",
    "s_pipe",
    "m_label|⌛7d: |color:yellow",
    "m_sumTokenOutSpeed|window:7d|align:true",
    "s_space",
    "m_sumTokenOut|window:7d|align:true",
    "s_space",
    "m_sumTokenTotalIn|window:7d|align:true",
    "s_space",
    "m_sumTokenHitRate|window:7d|align:true",
    "s_space",
    "m_sumApiCalls|window:7d|align:true",
    "s_space",
    "m_sumTokenCost|window:7d|align:true|valueOnly:true",
  ],
  git_info_all: [
    "m_label|⎇ Git: |color:yellow",
    "m_repo",
    "s_space",
    "m_branch",
    "s_space",
    "m_gitStatus",
    "s_space",
    "m_linesAdded",
    "s_space",
    "m_linesRemoved",
  ],
  context_all: [
    "m_label|Context: |color:yellow",
    "m_windowContext|display:used",
    "s_space",
    "m_contextSize",
    "s_space",
    "m_contextWindowSize",
    "s_space",
    "m_contextUsedPercent",
    "s_space",
    "m_contextRemainingPercent",
  ],
  quote: [
    "m_quote|freq:120s|color:rainbow|lang:en|wrap:~",
  ],
};

export const PRE_CLEANUP_STATUSLINE_PRESETS: Record<string, StatuslineTemplate> = {
  simple: [
    "m_pluginSource",
    "m_template|quota|type:quota",
    "m_template|balance|type:balance",
    "m_template|plugin_info|type:unknown",
  ],
  compact: [
    "m_label|💳: |color:blue",
    "m_provider",
    "/",
    "m_model",
    "s_pipe|wrap:true",
    "m_label|📜: |color:yellow",
    "m_windowContext|display:used",
    "s_space",
    "m_contextSize|valueOnly:true",
    "/",
    "m_contextWindowSize|valueOnly:true",
    "s_pipe|wrap:true",
    "m_label|▦: |color:yellow",
    "m_memUsage|valueOnly:true",
    "s_newline",

    "m_template|tickline-slim",
    "s_newline",

    "m_label|🗪 : |color:orange",
    "m_accTokenOutSpeed|scope:session",
    "s_space",
    "m_accTokenOut|scope:session",
    "s_space",
    "m_accTokenTotalIn|scope:session",
    "s_space",
    "m_accTokenHitRate|scope:session",
    "s_space",
    "m_accApiCalls|scope:session",
    "s_pipe|wrap:true",
    "m_label|⏱️: |color:yellow",
    "m_accApiMs|scope:session|valueOnly:true",
    "s_space",
    "m_label|🪙: |color:yellow",
    "m_accTokenCost|scope:session|valueOnly:true",
    "s_newline",

    "m_label|📦: |color:orange",
    "m_accTokenOutSpeed|scope:project",
    "s_space",
    "m_accTokenOut|scope:project",
    "s_space",
    "m_accTokenTotalIn|scope:project",
    "s_space",
    "m_accTokenHitRate|scope:project",
    "s_space",
    "m_accApiCalls|scope:project",
    "s_pipe|wrap:true",
    "m_template|git_info",
    "s_newline",

    "m_template|quota_all_compact|type:quota",
    "m_template|balance|type:balance",
    "s_newline",
    "m_template|quote"
  ],
  standard: [
    "m_template|information",
    "s_space",
    "m_template|mem_info",
    "s_pipe|wrap:true",
    "m_version|color:yellow",
    "s_newline",
    "m_template|tick_eval",
    "s_newline",
    "m_template|combline1",
    "s_newline",
    "m_template|combline2",
    "s_newline",
    "m_pluginSource",
    "m_template|quota|type:quota",
    "m_template|balance|type:balance",
    "s_space",
    "m_template|git_info",
  ],
  abundant: [
    "m_template|information",
    "s_space",
    "m_template|mem_info",
    "s_pipe|wrap:true",
    "m_version|color:yellow",
    "s_newline",
    "m_template|git_info_all",
    "s_pipe|wrap:true",
    "m_template|quote",
    "s_newline",
    "m_label|⚡Tick-tock: |color:cyan",
    "m_template|tokens_tick",
    "s_newline",
    "m_label|🟢Session:   |color:orange",
    "m_template|tokens_acc|scope:session",
    "s_newline",
    "m_label|🟢Project:   |color:orange",
    "m_template|tokens_acc|scope:project",
    "s_newline",
    "m_label|⌛5h-align:  |color:yellow",
    "m_template|tokens_stat|window:5h|align:true",
    "s_pipe|wrap:true",
    "m_sumTtlStatus|window:5h|align:true",
    "s_newline",
    "m_label|⌛7d-align:  |color:yellow",
    "m_template|tokens_stat|window:7d|align:true",
    "s_pipe|wrap:true",
    "m_sumTtlStatus|window:7d|align:true",
    "s_newline",
    "m_pluginSource",
    "m_template|quota_all|type:quota",
    "m_template|balance|type:balance",
    "s_space",
    "m_quota|term:long|display:remaining|nulldrop:true"
  ],
  "standard-slim": [
    "[",
    "m_provider",
    "/",
    "m_model",
    "] ",
    "m_label|📜: |color:yellow",
    "m_windowContext|display:used",
    "s_space",
    "m_contextWindowSize|valueOnly:true",
    "s_pipe|wrap:true",
    "m_label|▦: |color:yellow",
    "m_windowMemUsage|display:used",
    "s_space",
    "m_memUsage|valueOnly:true",
    "s_pipe|wrap:true",
    "m_label|⏱️: |color:yellow",
    "m_accApiMs|scope:session|valueOnly:true",
    "s_space",
    "m_label|🪙: |color:yellow",
    "m_accTokenCost|scope:session|valueOnly:true",
    "s_pipe|wrap:true",
    "m_version|color:yellow",
    "s_newline",
    "m_template|tickline-slim",
    "s_space",
    "m_template|quote",
    "s_newline",
    "m_template|combline1-slim",
    "s_newline",
    "m_template|combline2-slim",
    "s_newline",
    "m_template|quota_all|type:quota",
    "m_template|balance|type:balance",
    "s_space",
    "m_template|git_info"
  ],
};
